[tool.poetry]
name = "anaconda-investments"
version = "0.1.0"
description = ""
authors = ["Stu"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
pytest = "^8.3.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
